apiVersion: v1
kind: Service
metadata:
  name: md-svc
spec:
  selector:
    app: md
  ports:
    - protocol: TCP
      name: nginx
      port: 9001
      targetPort: 80
    - protocol: TCP
      name: multitool
      port: 9002
      targetPort: 8080